name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'README.md'

jobs:
  build:
    name: Linux-JDK${{ matrix.jdk }}
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        jdk: [17, 21]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'
          cache: maven
      - name: Build and test
        run: mvn clean install
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-reports
          path: '**/surefire-reports/*.txt'
        

